// Senior recruiters — IIT KGP AI Dept 2026, with interview patterns
// compiled from real candidate experiences (Glassdoor, GfG, Medium, InterviewBit).
export const SEED_RECRUITERS = [
  { company: "Qualcomm", hires: 1, type: "Product/Lab", dsa_bar: "Med→Med-Hard",
    pattern: "OA: aptitude + C/C++ + optional ML section. Then 2–3 technical rounds: 1 easy + 1 medium LeetCode, CNN param-count math, PyTorch (causal masking, GQA, MoE), deep project grilling. HR last.",
    focus: "Strings/arrays mediums + thesis (transformers, attention). Ready to code CNN param count & explain LoRA.", sort_idx: 1 },
  { company: "Microsoft", hires: 1, type: "Product/Lab", dsa_bar: "Med-Hard",
    pattern: "Classic SDE loop: OA (2 med ~90 min), then 2–3 interviews of 1–2 mediums with follow-ups, some design-lite. Strong on trees, graphs, DP.",
    focus: "Full NeetCode coverage. Trees/graphs/DP automatic. Talk while coding.", sort_idx: 2 },
  { company: "Apple", hires: 1, type: "Product/Lab", dsa_bar: "Med-Hard",
    pattern: "Team-dependent. Coding rounds (arrays/strings/DP) + deep project discussion. Values clean code & edge cases.",
    focus: "Mediums + clean implementation. Polish strongest 2 projects.", sort_idx: 3 },
  { company: "Samsung Research (Delhi/Noida)", hires: 2, type: "Product/Lab", dsa_bar: "Med (STL often banned)",
    pattern: "3 OA rounds (aptitude MCQ 60q/60min + coding) then technical + HR. Trees, basic DP, pointers, graphs (cycle detect, BFS shortest path), sorting w/ complexity limits. STL often NOT allowed — implement from scratch. Pen-paper coding + ML/DL from resume.",
    focus: "Implement structures WITHOUT library helpers. Graph BFS/DFS, cycle detection. Revise ML basics.", sort_idx: 4 },
  { company: "Walmart", hires: 1, type: "Product/Lab", dsa_bar: "Med-Hard",
    pattern: "OA (DSA-heavy: arrays, strings, DP) then 2–3 rounds. Solid medium-hard array/DP problems.",
    focus: "Array/String/DP mediums-hards — maps to Weeks 1–3 & 14–16.", sort_idx: 5 },
  { company: "Nutanix", hires: 1, type: "Product/Lab", dsa_bar: "Med-Hard",
    pattern: "OA + technical rounds, OS/systems flavor alongside DSA. Mediums on arrays/strings/LL.",
    focus: "Mediums + brush OS fundamentals (processes, memory, scheduling).", sort_idx: 6 },
  { company: "SAI Group", hires: 3, type: "AI/ML firm", dsa_bar: "Low-Med",
    pattern: "Top dept recruiter (3 hires). Applied AI focus — projects, ML fundamentals, problem-solving over LeetCode-hard.",
    focus: "Lead with thesis & projects. ML fundamentals (bias-variance, metrics, overfitting). Light DSA.", sort_idx: 7 },
  { company: "Aviso AI", hires: 2, type: "AI/ML firm", dsa_bar: "Low-Med",
    pattern: "Multiple quick rounds, similar Qs: LLMs, modeling, agentic agents, domain (sales/marketing forecasting). Skills test + presentation possible. Light on classic DSA.",
    focus: "LLM/RAG/agents talking points. Frame thesis around modeling. Prep a project presentation.", sort_idx: 8 },
  { company: "TCS Research", hires: 1, type: "AI/ML firm", dsa_bar: "Low-Med",
    pattern: "Research-oriented. Deep dive on publications/thesis, ML/DL theory, research aptitude.",
    focus: "Thesis is the centerpiece. Know your literature survey cold.", sort_idx: 9 },
  { company: "Mindstudio / YAL", hires: 1, type: "AI/ML firm", dsa_bar: "Low-Med",
    pattern: "Smaller AI firms — applied ML, project depth, practical Python coding.",
    focus: "Python fluency + applied ML. Portfolio projects.", sort_idx: 10 },
  { company: "Accenture AI / EY GDS", hires: 2, type: "Service/Consult", dsa_bar: "Low",
    pattern: "Aptitude + basic coding + fundamentals + HR/communication. Volume hiring.",
    focus: "Aptitude practice + basic DSA (easy-med). Communication & fit.", sort_idx: 11 },
  { company: "HCLSoftware / Wipro / Mphasis", hires: 2, type: "Service/Consult", dsa_bar: "Low",
    pattern: "Aptitude-heavy OA, basic coding, technical fundamentals, HR.",
    focus: "Easy-med DSA, aptitude, fundamentals. Lower bar — secure as backup.", sort_idx: 12 },
];
