// ─────────────────────────────────────────────────────────────────────────
// DSA PLACEMENT SEED — 271 problems mapped to the 23-week roadmap
// (Placement_Study_Plan_FULL). Per-week counts match the roadmap's targets.
// `companies` = how many of 23 well-known recruiters tag the problem (Google,
//   Amazon, Microsoft, Meta, Apple, Bloomberg, LinkedIn, TikTok, ByteDance,
//   Nvidia, Atlassian, Uber, Adobe, Goldman Sachs, Oracle, Salesforce, Walmart,
//   Flipkart, PayPal, Visa, Airbnb, DoorDash, Snap).
// `week` aligns to WEEK_TOPICS so the UI groups week → pattern → problem.
// ─────────────────────────────────────────────────────────────────────────

export type Difficulty = "EASY" | "MEDIUM" | "HARD";

export type SeedProblem = {
  title: string;
  companies: number;
  difficulty: Difficulty;
  pattern: string;
  week: number;
  link: string;
};

export const SEED_PROBLEMS: SeedProblem[] = [
  // ── Week 1: Python DS rebuild + Arrays & Hashing ──
  { title: "Two Sum", companies: 20, difficulty: "EASY", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/two-sum" },
  { title: "Group Anagrams", companies: 18, difficulty: "MEDIUM", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/group-anagrams" },
  { title: "First Missing Positive", companies: 15, difficulty: "HARD", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/first-missing-positive" },
  { title: "Valid Sudoku", companies: 15, difficulty: "MEDIUM", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/valid-sudoku" },
  { title: "Longest Common Prefix", companies: 12, difficulty: "EASY", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/longest-common-prefix" },
  { title: "Longest Consecutive Sequence", companies: 8, difficulty: "MEDIUM", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/longest-consecutive-sequence" },
  { title: "Top K Frequent Elements", companies: 8, difficulty: "MEDIUM", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/top-k-frequent-elements" },
  { title: "Product of Array Except Self", companies: 7, difficulty: "MEDIUM", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/product-of-array-except-self" },
  { title: "Valid Anagram", companies: 6, difficulty: "EASY", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/valid-anagram" },
  { title: "Subarray Sum Equals K", companies: 5, difficulty: "MEDIUM", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/subarray-sum-equals-k" },
  { title: "Majority Element", companies: 4, difficulty: "EASY", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/majority-element" },
  { title: "Contains Duplicate", companies: 2, difficulty: "EASY", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/contains-duplicate" },
  { title: "Encode and Decode Strings", companies: 0, difficulty: "MEDIUM", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/encode-and-decode-strings" },
  { title: "Find All Numbers Disappeared in an Array", companies: 0, difficulty: "EASY", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array" },
  { title: "Set Mismatch", companies: 0, difficulty: "EASY", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/set-mismatch" },
  // ── Week 2: Two Pointers + intro Sliding Window ──
  { title: "Trapping Rain Water", companies: 19, difficulty: "HARD", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/trapping-rain-water" },
  { title: "3Sum", companies: 16, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/3sum" },
  { title: "Container With Most Water", companies: 16, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/container-with-most-water" },
  { title: "Merge Sorted Array", companies: 15, difficulty: "EASY", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/merge-sorted-array" },
  { title: "Next Permutation", companies: 12, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/next-permutation" },
  { title: "Sort Colors", companies: 12, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/sort-colors" },
  { title: "4Sum", companies: 10, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/4sum" },
  { title: "Remove Duplicates from Sorted Array", companies: 9, difficulty: "EASY", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array" },
  { title: "3Sum Closest", companies: 8, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/3sum-closest" },
  { title: "Valid Palindrome", companies: 3, difficulty: "EASY", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/valid-palindrome" },
  { title: "Move Zeroes", companies: 2, difficulty: "EASY", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/move-zeroes" },
  { title: "Two Sum II - Input Array Is Sorted", companies: 1, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted" },
  // ── Week 3: Sliding Window (full) ──
  { title: "Longest Substring Without Repeating Characters", companies: 19, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/longest-substring-without-repeating-characters" },
  { title: "Minimum Window Substring", companies: 15, difficulty: "HARD", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/minimum-window-substring" },
  { title: "Best Time to Buy and Sell Stock", companies: 13, difficulty: "EASY", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock" },
  { title: "Sliding Window Maximum", companies: 5, difficulty: "HARD", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/sliding-window-maximum" },
  { title: "Minimum Size Subarray Sum", companies: 4, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/minimum-size-subarray-sum" },
  { title: "Longest Repeating Character Replacement", companies: 2, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/longest-repeating-character-replacement" },
  { title: "Find All Anagrams in a String", companies: 1, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/find-all-anagrams-in-a-string" },
  { title: "Maximum Points You Can Obtain from Cards", companies: 1, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards" },
  { title: "Permutation in String", companies: 1, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/permutation-in-string" },
  { title: "Fruit Into Baskets", companies: 0, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/fruit-into-baskets" },
  // ── Week 4: Stack ──
  { title: "Valid Parentheses", companies: 16, difficulty: "EASY", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/valid-parentheses" },
  { title: "Generate Parentheses", companies: 10, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/generate-parentheses" },
  { title: "Largest Rectangle in Histogram", companies: 9, difficulty: "HARD", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/largest-rectangle-in-histogram" },
  { title: "Simplify Path", companies: 8, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/simplify-path" },
  { title: "Min Stack", companies: 6, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/min-stack" },
  { title: "Asteroid Collision", companies: 3, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/asteroid-collision" },
  { title: "Basic Calculator", companies: 3, difficulty: "HARD", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/basic-calculator" },
  { title: "Daily Temperatures", companies: 3, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/daily-temperatures" },
  { title: "Decode String", companies: 3, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/decode-string" },
  { title: "Next Greater Element I", companies: 2, difficulty: "EASY", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/next-greater-element-i" },
  { title: "Car Fleet", companies: 1, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/car-fleet" },
  { title: "Evaluate Reverse Polish Notation", companies: 1, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/evaluate-reverse-polish-notation" },
  // ── Week 5: Binary Search ──
  { title: "Search in Rotated Sorted Array", companies: 18, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/search-in-rotated-sorted-array" },
  { title: "Median of Two Sorted Arrays", companies: 16, difficulty: "HARD", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/median-of-two-sorted-arrays" },
  { title: "Find First and Last Position of Element in Sorted Array", companies: 12, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array" },
  { title: "Search a 2D Matrix", companies: 10, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/search-a-2d-matrix" },
  { title: "Find Peak Element", companies: 9, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/find-peak-element" },
  { title: "Sqrt(x)", companies: 9, difficulty: "EASY", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/sqrtx" },
  { title: "Search Insert Position", companies: 7, difficulty: "EASY", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/search-insert-position" },
  { title: "Koko Eating Bananas", companies: 4, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/koko-eating-bananas" },
  { title: "Find Minimum in Rotated Sorted Array", companies: 3, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array" },
  { title: "Time Based Key-Value Store", companies: 2, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/time-based-key-value-store" },
  { title: "Split Array Largest Sum", companies: 1, difficulty: "HARD", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/split-array-largest-sum" },
  { title: "Binary Search", companies: 0, difficulty: "EASY", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/binary-search" },
  // ── Week 6: Linked List (part 1) + buffer/revision ──
  { title: "Merge Two Sorted Lists", companies: 14, difficulty: "EASY", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/merge-two-sorted-lists" },
  { title: "LRU Cache", companies: 11, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/lru-cache" },
  { title: "Remove Nth Node From End of List", companies: 8, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list" },
  { title: "Rotate List", companies: 8, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/rotate-list" },
  { title: "Swap Nodes in Pairs", companies: 8, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/swap-nodes-in-pairs" },
  { title: "Reverse Linked List", companies: 7, difficulty: "EASY", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/reverse-linked-list" },
  { title: "Copy List with Random Pointer", companies: 5, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/copy-list-with-random-pointer" },
  { title: "Reorder List", companies: 3, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/reorder-list" },
  { title: "Palindrome Linked List", companies: 1, difficulty: "EASY", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/palindrome-linked-list" },
  { title: "Middle of the Linked List", companies: 0, difficulty: "EASY", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/middle-of-the-linked-list" },
  { title: "Odd Even Linked List", companies: 0, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/odd-even-linked-list" },
  { title: "Remove Linked List Elements", companies: 0, difficulty: "EASY", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/remove-linked-list-elements" },
  // ── Week 7: Linked List (part 2) ──
  { title: "Merge k Sorted Lists", companies: 15, difficulty: "HARD", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/merge-k-sorted-lists" },
  { title: "Add Two Numbers", companies: 14, difficulty: "MEDIUM", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/add-two-numbers" },
  { title: "Reverse Linked List II", companies: 9, difficulty: "MEDIUM", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/reverse-linked-list-ii" },
  { title: "Reverse Nodes in k-Group", companies: 8, difficulty: "HARD", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/reverse-nodes-in-k-group" },
  { title: "Intersection of Two Linked Lists", companies: 5, difficulty: "EASY", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/intersection-of-two-linked-lists" },
  { title: "Find the Duplicate Number", companies: 3, difficulty: "MEDIUM", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/find-the-duplicate-number" },
  { title: "Linked List Cycle", companies: 3, difficulty: "EASY", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/linked-list-cycle" },
  { title: "Sort List", companies: 3, difficulty: "MEDIUM", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/sort-list" },
  { title: "Linked List Cycle II", companies: 1, difficulty: "MEDIUM", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/linked-list-cycle-ii" },
  { title: "Design Linked List", companies: 0, difficulty: "MEDIUM", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/design-linked-list" },
  // ── Week 8: Trees (part 1) — traversal & basics ──
  { title: "Binary Tree Zigzag Level Order Traversal", companies: 9, difficulty: "MEDIUM", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal" },
  { title: "Same Tree", companies: 9, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/same-tree" },
  { title: "Binary Tree Level Order Traversal", companies: 8, difficulty: "MEDIUM", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/binary-tree-level-order-traversal" },
  { title: "Binary Tree Inorder Traversal", companies: 7, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/binary-tree-inorder-traversal" },
  { title: "Maximum Depth of Binary Tree", companies: 7, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/maximum-depth-of-binary-tree" },
  { title: "Symmetric Tree", companies: 7, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/symmetric-tree" },
  { title: "Balanced Binary Tree", companies: 4, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/balanced-binary-tree" },
  { title: "Lowest Common Ancestor of a BST", companies: 3, difficulty: "MEDIUM", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree" },
  { title: "Diameter of Binary Tree", companies: 2, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/diameter-of-binary-tree" },
  { title: "Path Sum", companies: 2, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/path-sum" },
  { title: "Invert Binary Tree", companies: 1, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/invert-binary-tree" },
  { title: "Subtree of Another Tree", companies: 0, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/subtree-of-another-tree" },
  // ── Week 9: Trees (part 2) — BST & harder ──
  { title: "Validate Binary Search Tree", companies: 12, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/validate-binary-search-tree" },
  { title: "Binary Tree Maximum Path Sum", companies: 8, difficulty: "HARD", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/binary-tree-maximum-path-sum" },
  { title: "Construct Binary Tree from Preorder and Inorder", companies: 6, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal" },
  { title: "Flatten Binary Tree to Linked List", companies: 5, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list" },
  { title: "Lowest Common Ancestor of a Binary Tree", companies: 5, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree" },
  { title: "Convert Sorted Array to BST", companies: 4, difficulty: "EASY", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree" },
  { title: "Path Sum II", companies: 4, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/path-sum-ii" },
  { title: "Serialize and Deserialize Binary Tree", companies: 4, difficulty: "HARD", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree" },
  { title: "Binary Tree Right Side View", companies: 3, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/binary-tree-right-side-view" },
  { title: "Kth Smallest Element in a BST", companies: 2, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/kth-smallest-element-in-a-bst" },
  { title: "Count Good Nodes in Binary Tree", companies: 0, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/count-good-nodes-in-binary-tree" },
  { title: "Delete Node in a BST", companies: 0, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/delete-node-in-a-bst" },
  // ── Week 10: Tries + Heaps / Priority Queue ──
  { title: "Kth Largest Element in an Array", companies: 8, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/kth-largest-element-in-an-array" },
  { title: "Find Median from Data Stream", companies: 5, difficulty: "HARD", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/find-median-from-data-stream" },
  { title: "Word Search II", companies: 4, difficulty: "HARD", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/word-search-ii" },
  { title: "Design Add and Search Words Data Structure", companies: 3, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/design-add-and-search-words-data-structure" },
  { title: "Last Stone Weight", companies: 3, difficulty: "EASY", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/last-stone-weight" },
  { title: "Implement Trie (Prefix Tree)", companies: 2, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/implement-trie-prefix-tree" },
  { title: "K Closest Points to Origin", companies: 2, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/k-closest-points-to-origin" },
  { title: "Task Scheduler", companies: 2, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/task-scheduler" },
  { title: "Design Twitter", companies: 1, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/design-twitter" },
  { title: "Kth Largest Element in a Stream", companies: 1, difficulty: "EASY", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/kth-largest-element-in-a-stream" },
  { title: "Reorganize String", companies: 1, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/reorganize-string" },
  { title: "Top K Frequent Words", companies: 0, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/top-k-frequent-words" },
  // ── Week 11: Backtracking ──
  { title: "Combination Sum", companies: 14, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/combination-sum" },
  { title: "Word Search", companies: 14, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/word-search" },
  { title: "Permutations", companies: 11, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/permutations" },
  { title: "Combination Sum II", companies: 10, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/combination-sum-ii" },
  { title: "Letter Combinations of a Phone Number", companies: 10, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number" },
  { title: "N-Queens", companies: 10, difficulty: "HARD", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/n-queens" },
  { title: "Subsets", companies: 10, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/subsets" },
  { title: "Permutations II", companies: 8, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/permutations-ii" },
  { title: "Restore IP Addresses", companies: 8, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/restore-ip-addresses" },
  { title: "Subsets II", companies: 8, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/subsets-ii" },
  { title: "Combinations", companies: 7, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/combinations" },
  { title: "Palindrome Partitioning", companies: 1, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/palindrome-partitioning" },
  // ── Week 12: Graphs (part 1) — DFS/BFS ──
  { title: "Number of Islands", companies: 11, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/number-of-islands" },
  { title: "Course Schedule", companies: 8, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/course-schedule" },
  { title: "Course Schedule II", companies: 7, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/course-schedule-ii" },
  { title: "Walls and Gates", companies: 4, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/walls-and-gates" },
  { title: "Clone Graph", companies: 3, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/clone-graph" },
  { title: "Graph Valid Tree", companies: 3, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/graph-valid-tree" },
  { title: "Max Area of Island", companies: 3, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/max-area-of-island" },
  { title: "Rotting Oranges", companies: 3, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/rotting-oranges" },
  { title: "Surrounded Regions", companies: 2, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/surrounded-regions" },
  { title: "Number of Connected Components", companies: 1, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph" },
  { title: "Flood Fill", companies: 0, difficulty: "EASY", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/flood-fill" },
  { title: "Pacific Atlantic Water Flow", companies: 0, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/pacific-atlantic-water-flow" },
  // ── Week 13: Graphs (part 2) — Union Find / advanced ──
  { title: "Word Ladder", companies: 5, difficulty: "HARD", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/word-ladder" },
  { title: "Alien Dictionary", companies: 2, difficulty: "HARD", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/alien-dictionary" },
  { title: "Cheapest Flights Within K Stops", companies: 2, difficulty: "MEDIUM", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/cheapest-flights-within-k-stops" },
  { title: "Reconstruct Itinerary", companies: 2, difficulty: "HARD", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/reconstruct-itinerary" },
  { title: "Number of Provinces", companies: 1, difficulty: "MEDIUM", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/number-of-provinces" },
  { title: "Swim in Rising Water", companies: 1, difficulty: "HARD", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/swim-in-rising-water" },
  { title: "Find the Town Judge", companies: 0, difficulty: "EASY", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/find-the-town-judge" },
  { title: "Min Cost to Connect All Points", companies: 0, difficulty: "MEDIUM", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/min-cost-to-connect-all-points" },
  { title: "Network Delay Time", companies: 0, difficulty: "MEDIUM", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/network-delay-time" },
  { title: "Redundant Connection", companies: 0, difficulty: "MEDIUM", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/redundant-connection" },
  // ── Week 14: 1-D Dynamic Programming ──
  { title: "Longest Palindromic Substring", companies: 15, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/longest-palindromic-substring" },
  { title: "Decode Ways", companies: 13, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/decode-ways" },
  { title: "Climbing Stairs", companies: 12, difficulty: "EASY", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/climbing-stairs" },
  { title: "House Robber", companies: 9, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/house-robber" },
  { title: "Maximum Product Subarray", companies: 7, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/maximum-product-subarray" },
  { title: "Coin Change", companies: 5, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/coin-change" },
  { title: "House Robber II", companies: 4, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/house-robber-ii" },
  { title: "Word Break", companies: 4, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/word-break" },
  { title: "Longest Increasing Subsequence", companies: 3, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/longest-increasing-subsequence" },
  { title: "Palindromic Substrings", companies: 3, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/palindromic-substrings" },
  { title: "Partition Equal Subset Sum", companies: 2, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/partition-equal-subset-sum" },
  { title: "Min Cost Climbing Stairs", companies: 0, difficulty: "EASY", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/min-cost-climbing-stairs" },
  // ── Week 15: 2-D Dynamic Programming (part 1) ──
  { title: "Unique Paths", companies: 11, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/unique-paths" },
  { title: "Minimum Path Sum", companies: 10, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/minimum-path-sum" },
  { title: "Unique Paths II", companies: 9, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/unique-paths-ii" },
  { title: "Maximal Square", companies: 7, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/maximal-square" },
  { title: "Interleaving String", companies: 6, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/interleaving-string" },
  { title: "Best Time to Buy and Sell Stock with Cooldown", companies: 2, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown" },
  { title: "Longest Common Subsequence", companies: 2, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/longest-common-subsequence" },
  { title: "Dungeon Game", companies: 1, difficulty: "HARD", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/dungeon-game" },
  { title: "Coin Change II", companies: 0, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/coin-change-ii" },
  { title: "Target Sum", companies: 0, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/target-sum" },
  // ── Week 16: 2-D Dynamic Programming (part 2) ──
  { title: "Edit Distance", companies: 11, difficulty: "MEDIUM", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/edit-distance" },
  { title: "Maximal Rectangle", companies: 11, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/maximal-rectangle" },
  { title: "Regular Expression Matching", companies: 10, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/regular-expression-matching" },
  { title: "Wildcard Matching", companies: 10, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/wildcard-matching" },
  { title: "Longest Valid Parentheses", companies: 9, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/longest-valid-parentheses" },
  { title: "Distinct Subsequences", companies: 3, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/distinct-subsequences" },
  { title: "Longest Increasing Path in a Matrix", companies: 3, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix" },
  { title: "Burst Balloons", companies: 2, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/burst-balloons" },
  { title: "Minimum Cost to Cut a Stick", companies: 0, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/min-cost-to-cut-a-stick" },
  { title: "Stone Game", companies: 0, difficulty: "MEDIUM", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/stone-game" },
  // ── Week 17: Greedy + Intervals ──
  { title: "Merge Intervals", companies: 21, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/merge-intervals" },
  { title: "Maximum Subarray", companies: 17, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/maximum-subarray" },
  { title: "Jump Game", companies: 15, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/jump-game" },
  { title: "Jump Game II", companies: 15, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/jump-game-ii" },
  { title: "Insert Interval", companies: 11, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/insert-interval" },
  { title: "Meeting Rooms II", companies: 5, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/meeting-rooms-ii" },
  { title: "Gas Station", companies: 3, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/gas-station" },
  { title: "Minimum Arrows to Burst Balloons", companies: 2, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons" },
  { title: "Hand of Straights", companies: 0, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/hand-of-straights" },
  { title: "Non-overlapping Intervals", companies: 0, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/non-overlapping-intervals" },
  { title: "Partition Labels", companies: 0, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/partition-labels" },
  { title: "Valid Parenthesis String", companies: 0, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/valid-parenthesis-string" },
  // ── Week 18: Math & Geometry + Bit Manipulation ──
  { title: "Spiral Matrix", companies: 14, difficulty: "MEDIUM", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/spiral-matrix" },
  { title: "Pow(x, n)", companies: 13, difficulty: "MEDIUM", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/powx-n" },
  { title: "Rotate Image", companies: 12, difficulty: "MEDIUM", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/rotate-image" },
  { title: "Set Matrix Zeroes", companies: 10, difficulty: "MEDIUM", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/set-matrix-zeroes" },
  { title: "Plus One", companies: 9, difficulty: "EASY", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/plus-one" },
  { title: "Multiply Strings", companies: 8, difficulty: "MEDIUM", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/multiply-strings" },
  { title: "Missing Number", companies: 3, difficulty: "EASY", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/missing-number" },
  { title: "Single Number", companies: 3, difficulty: "EASY", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/single-number" },
  { title: "Happy Number", companies: 2, difficulty: "EASY", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/happy-number" },
  { title: "Reverse Bits", companies: 2, difficulty: "EASY", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/reverse-bits" },
  { title: "Counting Bits", companies: 1, difficulty: "EASY", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/counting-bits" },
  { title: "Number of 1 Bits", companies: 0, difficulty: "EASY", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/number-of-1-bits" },
  // ── Week 19: Buffer + full Phase A–C revision ──
  { title: "Text Justification", companies: 16, difficulty: "HARD", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/text-justification" },
  { title: "Integer to Roman", companies: 15, difficulty: "MEDIUM", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/integer-to-roman" },
  { title: "Roman to Integer", companies: 11, difficulty: "EASY", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/roman-to-integer" },
  { title: "String to Integer (atoi)", companies: 11, difficulty: "MEDIUM", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/string-to-integer-atoi" },
  { title: "Zigzag Conversion", companies: 10, difficulty: "MEDIUM", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/zigzag-conversion" },
  { title: "Add Binary", companies: 8, difficulty: "EASY", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/add-binary" },
  { title: "Count and Say", companies: 7, difficulty: "MEDIUM", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/count-and-say" },
  { title: "Valid Number", companies: 6, difficulty: "HARD", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/valid-number" },
  { title: "Rotate Array", companies: 4, difficulty: "MEDIUM", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/rotate-array" },
  { title: "Excel Sheet Column Number", companies: 0, difficulty: "EASY", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/excel-sheet-column-number" },
  // ── Week 20: Timed OA simulation — mixed ──
  { title: "Insert Delete GetRandom O(1)", companies: 7, difficulty: "MEDIUM", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/insert-delete-getrandom-o1" },
  { title: "Substring with Concatenation of All Words", companies: 6, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/substring-with-concatenation-of-all-words" },
  { title: "Maximum Profit in Job Scheduling", companies: 5, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/maximum-profit-in-job-scheduling" },
  { title: "Word Break II", companies: 4, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/word-break-ii" },
  { title: "Longest String Chain", companies: 3, difficulty: "MEDIUM", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/longest-string-chain" },
  { title: "Maximum Frequency Stack", companies: 3, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/maximum-frequency-stack" },
  { title: "String Compression", companies: 3, difficulty: "MEDIUM", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/string-compression" },
  { title: "The Skyline Problem", companies: 3, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/the-skyline-problem" },
  { title: "Design Hit Counter", companies: 2, difficulty: "MEDIUM", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/design-hit-counter" },
  { title: "Number of Islands II", companies: 2, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/number-of-islands-ii" },
  { title: "Range Sum Query 2D Immutable", companies: 2, difficulty: "MEDIUM", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/range-sum-query-2d-immutable" },
  { title: "Shortest Path with Obstacles Elimination", companies: 2, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination" },
  { title: "Trapping Rain Water II", companies: 1, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/trapping-rain-water-ii" },
  { title: "Max Sum 3 Non-Overlapping Subarrays", companies: 0, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/maximum-sum-of-3-non-overlapping-subarrays" },
  { title: "Maximum Swap", companies: 0, difficulty: "MEDIUM", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/maximum-swap" },
  // ── Week 21: Company-tagged sets — Amazon/Microsoft/Google ──
  { title: "Largest Number", companies: 4, difficulty: "MEDIUM", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/largest-number" },
  { title: "Candy", companies: 3, difficulty: "HARD", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/candy" },
  { title: "Cherry Pickup", companies: 2, difficulty: "HARD", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/cherry-pickup" },
  { title: "Design Browser History", companies: 2, difficulty: "MEDIUM", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/design-browser-history" },
  { title: "Design In-Memory File System", companies: 2, difficulty: "HARD", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/design-in-memory-file-system" },
  { title: "Employee Free Time", companies: 2, difficulty: "HARD", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/employee-free-time" },
  { title: "Random Pick with Weight", companies: 2, difficulty: "MEDIUM", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/random-pick-with-weight" },
  { title: "Shortest Bridge", companies: 2, difficulty: "MEDIUM", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/shortest-bridge" },
  { title: "Sliding Window Median", companies: 2, difficulty: "HARD", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/sliding-window-median" },
  { title: "Snapshot Array", companies: 2, difficulty: "MEDIUM", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/snapshot-array" },
  { title: "Task Scheduler II", companies: 2, difficulty: "MEDIUM", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/task-scheduler-ii" },
  { title: "Design Search Autocomplete System", companies: 1, difficulty: "HARD", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/design-search-autocomplete-system" },
  { title: "Group Shifted Strings", companies: 1, difficulty: "MEDIUM", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/group-shifted-strings" },
  { title: "Logger Rate Limiter", companies: 1, difficulty: "EASY", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/logger-rate-limiter" },
  { title: "Meeting Rooms", companies: 0, difficulty: "EASY", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/meeting-rooms" },
  // ── Week 22: Company-tagged sets — bio-AI & general ML targets ──
  { title: "Design Tic-Tac-Toe", companies: 3, difficulty: "MEDIUM", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/design-tic-tac-toe" },
  { title: "Smallest Range Covering K Lists", companies: 2, difficulty: "HARD", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists" },
  { title: "Accounts Merge", companies: 1, difficulty: "MEDIUM", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/accounts-merge" },
  { title: "Car Pooling", companies: 1, difficulty: "MEDIUM", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/car-pooling" },
  { title: "Data Stream as Disjoint Intervals", companies: 1, difficulty: "HARD", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/data-stream-as-disjoint-intervals" },
  { title: "Evaluate Division", companies: 1, difficulty: "MEDIUM", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/evaluate-division" },
  { title: "Find K Pairs with Smallest Sums", companies: 1, difficulty: "MEDIUM", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums" },
  { title: "Frog Jump", companies: 1, difficulty: "HARD", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/frog-jump" },
  { title: "Number of Distinct Islands", companies: 1, difficulty: "MEDIUM", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/number-of-distinct-islands" },
  { title: "Remove Invalid Parentheses", companies: 1, difficulty: "HARD", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/remove-invalid-parentheses" },
  { title: "Russian Doll Envelopes", companies: 1, difficulty: "HARD", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/russian-doll-envelopes" },
  { title: "Two Sum III", companies: 1, difficulty: "EASY", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/two-sum-iii-data-structure-design" },
  // ── Week 23: Final polish — weak spots, speed ──
  { title: "Diameter of N-Ary Tree", companies: 1, difficulty: "MEDIUM", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/diameter-of-n-ary-tree" },
  { title: "Find K-th Smallest Pair Distance", companies: 1, difficulty: "HARD", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/find-k-th-smallest-pair-distance" },
  { title: "IPO", companies: 1, difficulty: "HARD", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/ipo" },
  { title: "Kth Smallest in Sorted Matrix", companies: 1, difficulty: "MEDIUM", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix" },
  { title: "Vertical Order Traversal of a Binary Tree", companies: 1, difficulty: "HARD", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree" },
  { title: "Design Circular Queue", companies: 0, difficulty: "MEDIUM", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/design-circular-queue" },
  { title: "Expression Add Operators", companies: 0, difficulty: "HARD", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/expression-add-operators" },
  { title: "Integer to English Words", companies: 0, difficulty: "HARD", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/integer-to-english-words" },
  { title: "Longest Word in Dictionary", companies: 0, difficulty: "MEDIUM", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/longest-word-in-dictionary" },
  { title: "Word Wrap", companies: 0, difficulty: "HARD", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/text-justification-ii" },
];

// Week topic labels — mirror the 23-week roadmap. Used for week headers.
export const WEEK_TOPICS: Record<number, string> = {
  1: "Python DS rebuild + Arrays & Hashing",
  2: "Two Pointers + intro Sliding Window",
  3: "Sliding Window (full)",
  4: "Stack",
  5: "Binary Search",
  6: "Linked List (part 1) + buffer/revision",
  7: "Linked List (part 2)",
  8: "Trees (part 1) — traversal & basics",
  9: "Trees (part 2) — BST & harder",
  10: "Tries + Heaps / Priority Queue",
  11: "Backtracking",
  12: "Graphs (part 1) — DFS/BFS",
  13: "Graphs (part 2) — Union Find / advanced",
  14: "1-D Dynamic Programming",
  15: "2-D Dynamic Programming (part 1)",
  16: "2-D Dynamic Programming (part 2)",
  17: "Greedy + Intervals",
  18: "Math & Geometry + Bit Manipulation",
  19: "Buffer + full Phase A–C revision",
  20: "Timed OA simulation — mixed",
  21: "Company-tagged sets — Amazon/Microsoft/Google",
  22: "Company-tagged sets — bio-AI & general ML targets",
  23: "Final polish — weak spots, speed",
};

// Week date ranges from the roadmap (optional UI use).
export const WEEK_DATES: Record<number, string> = {
  1: "22 Jun – 28 Jun",
  2: "29 Jun – 05 Jul",
  3: "06 Jul – 12 Jul",
  4: "13 Jul – 19 Jul",
  5: "20 Jul – 26 Jul",
  6: "27 Jul – 02 Aug",
  7: "03 Aug – 09 Aug",
  8: "10 Aug – 16 Aug",
  9: "17 Aug – 23 Aug",
  10: "24 Aug – 30 Aug",
  11: "31 Aug – 06 Sep",
  12: "07 Sep – 13 Sep",
  13: "14 Sep – 20 Sep",
  14: "21 Sep – 27 Sep",
  15: "28 Sep – 04 Oct",
  16: "05 Oct – 11 Oct",
  17: "12 Oct – 18 Oct",
  18: "19 Oct – 25 Oct",
  19: "26 Oct – 01 Nov",
  20: "02 Nov – 08 Nov",
  21: "09 Nov – 15 Nov",
  22: "16 Nov – 22 Nov",
  23: "23 Nov – 29 Nov",
};

// Phase grouping (Foundation / Core / Advanced / Mock).
export const PHASES: { name: string; weeks: number[]; blurb: string }[] = [
  { name: "Foundation", weeks: [1, 2, 3, 4, 5, 6], blurb: "Arrays → Binary Search → Linked Lists" },
  { name: "Core", weeks: [7, 8, 9, 10, 11, 12, 13], blurb: "Trees, Tries, Heaps, Backtracking, Graphs" },
  { name: "Advanced", weeks: [14, 15, 16, 17, 18, 19], blurb: "DP, Greedy, Intervals, Math, Bits" },
  { name: "Mock & Polish", weeks: [20, 21, 22, 23], blurb: "Timed OAs, company sets, revision" },
];