// Auto-generated from your 23-week plan (top-60 highest-frequency problems).
export const SEED_PROBLEMS = [
  { title: "Trapping Rain Water", companies: 11, difficulty: "HARD", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/trapping-rain-water" },
  { title: "Longest Substring Without Repeating Characters", companies: 11, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/longest-substring-without-repeating-characters" },
  { title: "Search in Rotated Sorted Array", companies: 11, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/search-in-rotated-sorted-array" },
  { title: "Jump Game", companies: 11, difficulty: "MEDIUM", pattern: "Dynamic Programming", week: 14, link: "https://leetcode.com/problems/jump-game" },
  { title: "First Missing Positive", companies: 11, difficulty: "HARD", pattern: "Hash Table", week: 1, link: "https://leetcode.com/problems/first-missing-positive" },
  { title: "Two Sum", companies: 10, difficulty: "EASY", pattern: "Hash Table", week: 1, link: "https://leetcode.com/problems/two-sum" },
  { title: "Median of Two Sorted Arrays", companies: 10, difficulty: "HARD", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/median-of-two-sorted-arrays" },
  { title: "Group Anagrams", companies: 10, difficulty: "MEDIUM", pattern: "Hash Table", week: 1, link: "https://leetcode.com/problems/group-anagrams" },
  { title: "Jump Game II", companies: 10, difficulty: "MEDIUM", pattern: "Dynamic Programming", week: 14, link: "https://leetcode.com/problems/jump-game-ii" },
  { title: "Integer to Roman", companies: 10, difficulty: "MEDIUM", pattern: "Hash Table", week: 1, link: "https://leetcode.com/problems/integer-to-roman" },
  { title: "3Sum", companies: 10, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/3sum" },
  { title: "Merge Intervals", companies: 10, difficulty: "MEDIUM", pattern: "Sorting", week: 5, link: "https://leetcode.com/problems/merge-intervals" },
  { title: "Container With Most Water", companies: 10, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/container-with-most-water" },
  { title: "Decode Ways", companies: 10, difficulty: "MEDIUM", pattern: "Dynamic Programming", week: 14, link: "https://leetcode.com/problems/decode-ways" },
  { title: "Add Two Numbers", companies: 9, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/add-two-numbers" },
  { title: "Valid Parentheses", companies: 9, difficulty: "EASY", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/valid-parentheses" },
  { title: "Maximum Subarray", companies: 9, difficulty: "MEDIUM", pattern: "Dynamic Programming", week: 14, link: "https://leetcode.com/problems/maximum-subarray" },
  { title: "Rotate Image", companies: 9, difficulty: "MEDIUM", pattern: "Matrix", week: 18, link: "https://leetcode.com/problems/rotate-image" },
  { title: "Maximal Rectangle", companies: 9, difficulty: "HARD", pattern: "Dynamic Programming", week: 14, link: "https://leetcode.com/problems/maximal-rectangle" },
  { title: "Longest Palindromic Substring", companies: 9, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/longest-palindromic-substring" },
  { title: "Roman to Integer", companies: 9, difficulty: "EASY", pattern: "Hash Table", week: 1, link: "https://leetcode.com/problems/roman-to-integer" },
  { title: "Merge Two Sorted Lists", companies: 9, difficulty: "EASY", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/merge-two-sorted-lists" },
  { title: "Pow(x, n)", companies: 9, difficulty: "MEDIUM", pattern: "Math", week: 18, link: "https://leetcode.com/problems/powx-n" },
  { title: "Sort Colors", companies: 9, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/sort-colors" },
  { title: "Longest Common Prefix", companies: 8, difficulty: "EASY", pattern: "String", week: 1, link: "https://leetcode.com/problems/longest-common-prefix" },
  { title: "Text Justification", companies: 8, difficulty: "HARD", pattern: "Array", week: 1, link: "https://leetcode.com/problems/text-justification" },
  { title: "Insert Interval", companies: 8, difficulty: "MEDIUM", pattern: "Array", week: 1, link: "https://leetcode.com/problems/insert-interval" },
  { title: "String to Integer (atoi)", companies: 8, difficulty: "MEDIUM", pattern: "String", week: 1, link: "https://leetcode.com/problems/string-to-integer-atoi" },
  { title: "Wildcard Matching", companies: 8, difficulty: "HARD", pattern: "Dynamic Programming", week: 14, link: "https://leetcode.com/problems/wildcard-matching" },
  { title: "Minimum Path Sum", companies: 8, difficulty: "MEDIUM", pattern: "Dynamic Programming", week: 14, link: "https://leetcode.com/problems/minimum-path-sum" },
  { title: "Merge Sorted Array", companies: 8, difficulty: "EASY", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/merge-sorted-array" },
  { title: "Merge k Sorted Lists", companies: 8, difficulty: "HARD", pattern: "Heap (Priority Queue)", week: 10, link: "https://leetcode.com/problems/merge-k-sorted-lists" },
  { title: "Climbing Stairs", companies: 8, difficulty: "EASY", pattern: "Dynamic Programming", week: 14, link: "https://leetcode.com/problems/climbing-stairs" },
  { title: "Letter Combinations of a Phone Number", companies: 8, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number" },
  { title: "Spiral Matrix", companies: 8, difficulty: "MEDIUM", pattern: "Matrix", week: 18, link: "https://leetcode.com/problems/spiral-matrix" },
  { title: "Word Search", companies: 8, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/word-search" },
  { title: "Remove Duplicates from Sorted Array", companies: 8, difficulty: "EASY", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array" },
  { title: "Valid Sudoku", companies: 8, difficulty: "MEDIUM", pattern: "Matrix", week: 18, link: "https://leetcode.com/problems/valid-sudoku" },
  { title: "Set Matrix Zeroes", companies: 8, difficulty: "MEDIUM", pattern: "Matrix", week: 18, link: "https://leetcode.com/problems/set-matrix-zeroes" },
  { title: "Unique Paths", companies: 8, difficulty: "MEDIUM", pattern: "Dynamic Programming", week: 14, link: "https://leetcode.com/problems/unique-paths" },
  { title: "Minimum Window Substring", companies: 8, difficulty: "HARD", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/minimum-window-substring" },
  { title: "Validate Binary Search Tree", companies: 8, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/validate-binary-search-tree" },
  { title: "N-Queens", companies: 8, difficulty: "HARD", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/n-queens" },
  { title: "Zigzag Conversion", companies: 8, difficulty: "MEDIUM", pattern: "String", week: 1, link: "https://leetcode.com/problems/zigzag-conversion" },
  { title: "Combination Sum", companies: 8, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/combination-sum" },
  { title: "Permutations", companies: 8, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/permutations" },
  { title: "4Sum", companies: 7, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/4sum" },
  { title: "Find the Index of the First Occurrence in a String", companies: 7, difficulty: "EASY", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string" },
  { title: "Add Binary", companies: 7, difficulty: "EASY", pattern: "String", week: 1, link: "https://leetcode.com/problems/add-binary" },
  { title: "Same Tree", companies: 7, difficulty: "EASY", pattern: "Tree", week: 8, link: "https://leetcode.com/problems/same-tree" },
  { title: "Search a 2D Matrix", companies: 7, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/search-a-2d-matrix" },
  { title: "3Sum Closest", companies: 7, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/3sum-closest" },
  { title: "Generate Parentheses", companies: 7, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/generate-parentheses" },
  { title: "Palindrome Number", companies: 7, difficulty: "EASY", pattern: "Math", week: 18, link: "https://leetcode.com/problems/palindrome-number" },
  { title: "Next Permutation", companies: 7, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/next-permutation" },
  { title: "Largest Rectangle in Histogram", companies: 7, difficulty: "HARD", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/largest-rectangle-in-histogram" },
  { title: "Find First and Last Position of Element in Sorted Array", companies: 7, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array" },
  { title: "Subsets", companies: 7, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/subsets" },
  { title: "Sqrt(x)", companies: 7, difficulty: "EASY", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/sqrtx" },
  { title: "Longest Valid Parentheses", companies: 7, difficulty: "HARD", pattern: "Dynamic Programming", week: 14, link: "https://leetcode.com/problems/longest-valid-parentheses" },
];