// ─────────────────────────────────────────────────────────────────────────
// DSA PLACEMENT SEED — 271 problems mapped to the 23-week roadmap
// (Placement_Study_Plan_FULL). Per-week counts match the roadmap's targets.
// `companies` = how many of 23 well-known recruiters tag the problem (Google,
//   Amazon, Microsoft, Meta, Apple, Bloomberg, LinkedIn, TikTok, ByteDance,
//   Nvidia, Atlassian, Uber, Adobe, Goldman Sachs, Oracle, Salesforce, Walmart,
//   Flipkart, PayPal, Visa, Airbnb, DoorDash, Snap).
// `link`    = LeetCode problem page.
// `youtube` = YouTube search prefilled with 'NeetCode <title>' — lands on the
//   brute-force→optimal walkthrough (NeetCode for most; other channels fall back).
// `week` aligns to WEEK_TOPICS so the UI groups week → pattern → problem.
// ─────────────────────────────────────────────────────────────────────────

export type Difficulty = "EASY" | "MEDIUM" | "HARD";

export type SeedProblem = {
  title: string;
  companies: number;
  difficulty: Difficulty;
  pattern: string;
  week: number;
  link: string;
  youtube: string;
};

export const SEED_PROBLEMS: SeedProblem[] = [
  // ── Week 1: Python DS rebuild + Arrays & Hashing ──
  { title: "Two Sum", companies: 20, difficulty: "EASY", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/two-sum", youtube: "https://www.youtube.com/results?search_query=NeetCode+Two+Sum" },
  { title: "Group Anagrams", companies: 18, difficulty: "MEDIUM", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/group-anagrams", youtube: "https://www.youtube.com/results?search_query=NeetCode+Group+Anagrams" },
  { title: "First Missing Positive", companies: 15, difficulty: "HARD", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/first-missing-positive", youtube: "https://www.youtube.com/results?search_query=NeetCode+First+Missing+Positive" },
  { title: "Valid Sudoku", companies: 15, difficulty: "MEDIUM", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/valid-sudoku", youtube: "https://www.youtube.com/results?search_query=NeetCode+Valid+Sudoku" },
  { title: "Longest Common Prefix", companies: 12, difficulty: "EASY", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/longest-common-prefix", youtube: "https://www.youtube.com/results?search_query=NeetCode+Longest+Common+Prefix" },
  { title: "Longest Consecutive Sequence", companies: 8, difficulty: "MEDIUM", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/longest-consecutive-sequence", youtube: "https://www.youtube.com/results?search_query=NeetCode+Longest+Consecutive+Sequence" },
  { title: "Top K Frequent Elements", companies: 8, difficulty: "MEDIUM", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/top-k-frequent-elements", youtube: "https://www.youtube.com/results?search_query=NeetCode+Top+K+Frequent+Elements" },
  { title: "Product of Array Except Self", companies: 7, difficulty: "MEDIUM", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/product-of-array-except-self", youtube: "https://www.youtube.com/results?search_query=NeetCode+Product+of+Array+Except+Self" },
  { title: "Valid Anagram", companies: 6, difficulty: "EASY", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/valid-anagram", youtube: "https://www.youtube.com/results?search_query=NeetCode+Valid+Anagram" },
  { title: "Subarray Sum Equals K", companies: 5, difficulty: "MEDIUM", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/subarray-sum-equals-k", youtube: "https://www.youtube.com/results?search_query=NeetCode+Subarray+Sum+Equals+K" },
  { title: "Majority Element", companies: 4, difficulty: "EASY", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/majority-element", youtube: "https://www.youtube.com/results?search_query=NeetCode+Majority+Element" },
  { title: "Contains Duplicate", companies: 2, difficulty: "EASY", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/contains-duplicate", youtube: "https://www.youtube.com/results?search_query=NeetCode+Contains+Duplicate" },
  { title: "Encode and Decode Strings", companies: 0, difficulty: "MEDIUM", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/encode-and-decode-strings", youtube: "https://www.youtube.com/results?search_query=NeetCode+Encode+and+Decode+Strings" },
  { title: "Find All Numbers Disappeared in an Array", companies: 0, difficulty: "EASY", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array", youtube: "https://www.youtube.com/results?search_query=NeetCode+Find+All+Numbers+Disappeared+in+an+Array" },
  { title: "Set Mismatch", companies: 0, difficulty: "EASY", pattern: "Arrays & Hashing", week: 1, link: "https://leetcode.com/problems/set-mismatch", youtube: "https://www.youtube.com/results?search_query=NeetCode+Set+Mismatch" },
  // ── Week 2: Two Pointers + intro Sliding Window ──
  { title: "Trapping Rain Water", companies: 19, difficulty: "HARD", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/trapping-rain-water", youtube: "https://www.youtube.com/results?search_query=NeetCode+Trapping+Rain+Water" },
  { title: "3Sum", companies: 16, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/3sum", youtube: "https://www.youtube.com/results?search_query=NeetCode+3Sum" },
  { title: "Container With Most Water", companies: 16, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/container-with-most-water", youtube: "https://www.youtube.com/results?search_query=NeetCode+Container+With+Most+Water" },
  { title: "Merge Sorted Array", companies: 15, difficulty: "EASY", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/merge-sorted-array", youtube: "https://www.youtube.com/results?search_query=NeetCode+Merge+Sorted+Array" },
  { title: "Next Permutation", companies: 12, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/next-permutation", youtube: "https://www.youtube.com/results?search_query=NeetCode+Next+Permutation" },
  { title: "Sort Colors", companies: 12, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/sort-colors", youtube: "https://www.youtube.com/results?search_query=NeetCode+Sort+Colors" },
  { title: "4Sum", companies: 10, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/4sum", youtube: "https://www.youtube.com/results?search_query=NeetCode+4Sum" },
  { title: "Remove Duplicates from Sorted Array", companies: 9, difficulty: "EASY", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array", youtube: "https://www.youtube.com/results?search_query=NeetCode+Remove+Duplicates+from+Sorted+Array" },
  { title: "3Sum Closest", companies: 8, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/3sum-closest", youtube: "https://www.youtube.com/results?search_query=NeetCode+3Sum+Closest" },
  { title: "Valid Palindrome", companies: 3, difficulty: "EASY", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/valid-palindrome", youtube: "https://www.youtube.com/results?search_query=NeetCode+Valid+Palindrome" },
  { title: "Move Zeroes", companies: 2, difficulty: "EASY", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/move-zeroes", youtube: "https://www.youtube.com/results?search_query=NeetCode+Move+Zeroes" },
  { title: "Two Sum II - Input Array Is Sorted", companies: 1, difficulty: "MEDIUM", pattern: "Two Pointers", week: 2, link: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted", youtube: "https://www.youtube.com/results?search_query=NeetCode+Two+Sum+II+-+Input+Array+Is+Sorted" },
  // ── Week 3: Sliding Window (full) ──
  { title: "Longest Substring Without Repeating Characters", companies: 19, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/longest-substring-without-repeating-characters", youtube: "https://www.youtube.com/results?search_query=NeetCode+Longest+Substring+Without+Repeating+Characters" },
  { title: "Minimum Window Substring", companies: 15, difficulty: "HARD", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/minimum-window-substring", youtube: "https://www.youtube.com/results?search_query=NeetCode+Minimum+Window+Substring" },
  { title: "Best Time to Buy and Sell Stock", companies: 13, difficulty: "EASY", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock", youtube: "https://www.youtube.com/results?search_query=NeetCode+Best+Time+to+Buy+and+Sell+Stock" },
  { title: "Sliding Window Maximum", companies: 5, difficulty: "HARD", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/sliding-window-maximum", youtube: "https://www.youtube.com/results?search_query=NeetCode+Sliding+Window+Maximum" },
  { title: "Minimum Size Subarray Sum", companies: 4, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/minimum-size-subarray-sum", youtube: "https://www.youtube.com/results?search_query=NeetCode+Minimum+Size+Subarray+Sum" },
  { title: "Longest Repeating Character Replacement", companies: 2, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/longest-repeating-character-replacement", youtube: "https://www.youtube.com/results?search_query=NeetCode+Longest+Repeating+Character+Replacement" },
  { title: "Find All Anagrams in a String", companies: 1, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/find-all-anagrams-in-a-string", youtube: "https://www.youtube.com/results?search_query=NeetCode+Find+All+Anagrams+in+a+String" },
  { title: "Maximum Points You Can Obtain from Cards", companies: 1, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards", youtube: "https://www.youtube.com/results?search_query=NeetCode+Maximum+Points+You+Can+Obtain+from+Cards" },
  { title: "Permutation in String", companies: 1, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/permutation-in-string", youtube: "https://www.youtube.com/results?search_query=NeetCode+Permutation+in+String" },
  { title: "Fruit Into Baskets", companies: 0, difficulty: "MEDIUM", pattern: "Sliding Window", week: 3, link: "https://leetcode.com/problems/fruit-into-baskets", youtube: "https://www.youtube.com/results?search_query=NeetCode+Fruit+Into+Baskets" },
  // ── Week 4: Stack ──
  { title: "Valid Parentheses", companies: 16, difficulty: "EASY", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/valid-parentheses", youtube: "https://www.youtube.com/results?search_query=NeetCode+Valid+Parentheses" },
  { title: "Generate Parentheses", companies: 10, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/generate-parentheses", youtube: "https://www.youtube.com/results?search_query=NeetCode+Generate+Parentheses" },
  { title: "Largest Rectangle in Histogram", companies: 9, difficulty: "HARD", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/largest-rectangle-in-histogram", youtube: "https://www.youtube.com/results?search_query=NeetCode+Largest+Rectangle+in+Histogram" },
  { title: "Simplify Path", companies: 8, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/simplify-path", youtube: "https://www.youtube.com/results?search_query=NeetCode+Simplify+Path" },
  { title: "Min Stack", companies: 6, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/min-stack", youtube: "https://www.youtube.com/results?search_query=NeetCode+Min+Stack" },
  { title: "Asteroid Collision", companies: 3, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/asteroid-collision", youtube: "https://www.youtube.com/results?search_query=NeetCode+Asteroid+Collision" },
  { title: "Basic Calculator", companies: 3, difficulty: "HARD", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/basic-calculator", youtube: "https://www.youtube.com/results?search_query=NeetCode+Basic+Calculator" },
  { title: "Daily Temperatures", companies: 3, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/daily-temperatures", youtube: "https://www.youtube.com/results?search_query=NeetCode+Daily+Temperatures" },
  { title: "Decode String", companies: 3, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/decode-string", youtube: "https://www.youtube.com/results?search_query=NeetCode+Decode+String" },
  { title: "Next Greater Element I", companies: 2, difficulty: "EASY", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/next-greater-element-i", youtube: "https://www.youtube.com/results?search_query=NeetCode+Next+Greater+Element+I" },
  { title: "Car Fleet", companies: 1, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/car-fleet", youtube: "https://www.youtube.com/results?search_query=NeetCode+Car+Fleet" },
  { title: "Evaluate Reverse Polish Notation", companies: 1, difficulty: "MEDIUM", pattern: "Stack", week: 4, link: "https://leetcode.com/problems/evaluate-reverse-polish-notation", youtube: "https://www.youtube.com/results?search_query=NeetCode+Evaluate+Reverse+Polish+Notation" },
  // ── Week 5: Binary Search ──
  { title: "Search in Rotated Sorted Array", companies: 18, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/search-in-rotated-sorted-array", youtube: "https://www.youtube.com/results?search_query=NeetCode+Search+in+Rotated+Sorted+Array" },
  { title: "Median of Two Sorted Arrays", companies: 16, difficulty: "HARD", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/median-of-two-sorted-arrays", youtube: "https://www.youtube.com/results?search_query=NeetCode+Median+of+Two+Sorted+Arrays" },
  { title: "Find First and Last Position of Element in Sorted Array", companies: 12, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array", youtube: "https://www.youtube.com/results?search_query=NeetCode+Find+First+and+Last+Position+of+Element+in+Sorted+Array" },
  { title: "Search a 2D Matrix", companies: 10, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/search-a-2d-matrix", youtube: "https://www.youtube.com/results?search_query=NeetCode+Search+a+2D+Matrix" },
  { title: "Find Peak Element", companies: 9, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/find-peak-element", youtube: "https://www.youtube.com/results?search_query=NeetCode+Find+Peak+Element" },
  { title: "Sqrt(x)", companies: 9, difficulty: "EASY", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/sqrtx", youtube: "https://www.youtube.com/results?search_query=NeetCode+Sqrt%28x%29" },
  { title: "Search Insert Position", companies: 7, difficulty: "EASY", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/search-insert-position", youtube: "https://www.youtube.com/results?search_query=NeetCode+Search+Insert+Position" },
  { title: "Koko Eating Bananas", companies: 4, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/koko-eating-bananas", youtube: "https://www.youtube.com/results?search_query=NeetCode+Koko+Eating+Bananas" },
  { title: "Find Minimum in Rotated Sorted Array", companies: 3, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array", youtube: "https://www.youtube.com/results?search_query=NeetCode+Find+Minimum+in+Rotated+Sorted+Array" },
  { title: "Time Based Key-Value Store", companies: 2, difficulty: "MEDIUM", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/time-based-key-value-store", youtube: "https://www.youtube.com/results?search_query=NeetCode+Time+Based+Key-Value+Store" },
  { title: "Split Array Largest Sum", companies: 1, difficulty: "HARD", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/split-array-largest-sum", youtube: "https://www.youtube.com/results?search_query=NeetCode+Split+Array+Largest+Sum" },
  { title: "Binary Search", companies: 0, difficulty: "EASY", pattern: "Binary Search", week: 5, link: "https://leetcode.com/problems/binary-search", youtube: "https://www.youtube.com/results?search_query=NeetCode+Binary+Search" },
  // ── Week 6: Linked List (part 1) + buffer/revision ──
  { title: "Merge Two Sorted Lists", companies: 14, difficulty: "EASY", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/merge-two-sorted-lists", youtube: "https://www.youtube.com/results?search_query=NeetCode+Merge+Two+Sorted+Lists" },
  { title: "LRU Cache", companies: 11, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/lru-cache", youtube: "https://www.youtube.com/results?search_query=NeetCode+LRU+Cache" },
  { title: "Remove Nth Node From End of List", companies: 8, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list", youtube: "https://www.youtube.com/results?search_query=NeetCode+Remove+Nth+Node+From+End+of+List" },
  { title: "Rotate List", companies: 8, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/rotate-list", youtube: "https://www.youtube.com/results?search_query=NeetCode+Rotate+List" },
  { title: "Swap Nodes in Pairs", companies: 8, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/swap-nodes-in-pairs", youtube: "https://www.youtube.com/results?search_query=NeetCode+Swap+Nodes+in+Pairs" },
  { title: "Reverse Linked List", companies: 7, difficulty: "EASY", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/reverse-linked-list", youtube: "https://www.youtube.com/results?search_query=NeetCode+Reverse+Linked+List" },
  { title: "Copy List with Random Pointer", companies: 5, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/copy-list-with-random-pointer", youtube: "https://www.youtube.com/results?search_query=NeetCode+Copy+List+with+Random+Pointer" },
  { title: "Reorder List", companies: 3, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/reorder-list", youtube: "https://www.youtube.com/results?search_query=NeetCode+Reorder+List" },
  { title: "Palindrome Linked List", companies: 1, difficulty: "EASY", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/palindrome-linked-list", youtube: "https://www.youtube.com/results?search_query=NeetCode+Palindrome+Linked+List" },
  { title: "Middle of the Linked List", companies: 0, difficulty: "EASY", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/middle-of-the-linked-list", youtube: "https://www.youtube.com/results?search_query=NeetCode+Middle+of+the+Linked+List" },
  { title: "Odd Even Linked List", companies: 0, difficulty: "MEDIUM", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/odd-even-linked-list", youtube: "https://www.youtube.com/results?search_query=NeetCode+Odd+Even+Linked+List" },
  { title: "Remove Linked List Elements", companies: 0, difficulty: "EASY", pattern: "Linked List", week: 6, link: "https://leetcode.com/problems/remove-linked-list-elements", youtube: "https://www.youtube.com/results?search_query=NeetCode+Remove+Linked+List+Elements" },
  // ── Week 7: Linked List (part 2) ──
  { title: "Merge k Sorted Lists", companies: 15, difficulty: "HARD", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/merge-k-sorted-lists", youtube: "https://www.youtube.com/results?search_query=NeetCode+Merge+k+Sorted+Lists" },
  { title: "Add Two Numbers", companies: 14, difficulty: "MEDIUM", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/add-two-numbers", youtube: "https://www.youtube.com/results?search_query=NeetCode+Add+Two+Numbers" },
  { title: "Reverse Linked List II", companies: 9, difficulty: "MEDIUM", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/reverse-linked-list-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Reverse+Linked+List+II" },
  { title: "Reverse Nodes in k-Group", companies: 8, difficulty: "HARD", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/reverse-nodes-in-k-group", youtube: "https://www.youtube.com/results?search_query=NeetCode+Reverse+Nodes+in+k-Group" },
  { title: "Intersection of Two Linked Lists", companies: 5, difficulty: "EASY", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/intersection-of-two-linked-lists", youtube: "https://www.youtube.com/results?search_query=NeetCode+Intersection+of+Two+Linked+Lists" },
  { title: "Find the Duplicate Number", companies: 3, difficulty: "MEDIUM", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/find-the-duplicate-number", youtube: "https://www.youtube.com/results?search_query=NeetCode+Find+the+Duplicate+Number" },
  { title: "Linked List Cycle", companies: 3, difficulty: "EASY", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/linked-list-cycle", youtube: "https://www.youtube.com/results?search_query=NeetCode+Linked+List+Cycle" },
  { title: "Sort List", companies: 3, difficulty: "MEDIUM", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/sort-list", youtube: "https://www.youtube.com/results?search_query=NeetCode+Sort+List" },
  { title: "Linked List Cycle II", companies: 1, difficulty: "MEDIUM", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/linked-list-cycle-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Linked+List+Cycle+II" },
  { title: "Design Linked List", companies: 0, difficulty: "MEDIUM", pattern: "Linked List", week: 7, link: "https://leetcode.com/problems/design-linked-list", youtube: "https://www.youtube.com/results?search_query=NeetCode+Design+Linked+List" },
  // ── Week 8: Trees (part 1) — traversal & basics ──
  { title: "Binary Tree Zigzag Level Order Traversal", companies: 9, difficulty: "MEDIUM", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal", youtube: "https://www.youtube.com/results?search_query=NeetCode+Binary+Tree+Zigzag+Level+Order+Traversal" },
  { title: "Same Tree", companies: 9, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/same-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Same+Tree" },
  { title: "Binary Tree Level Order Traversal", companies: 8, difficulty: "MEDIUM", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/binary-tree-level-order-traversal", youtube: "https://www.youtube.com/results?search_query=NeetCode+Binary+Tree+Level+Order+Traversal" },
  { title: "Binary Tree Inorder Traversal", companies: 7, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/binary-tree-inorder-traversal", youtube: "https://www.youtube.com/results?search_query=NeetCode+Binary+Tree+Inorder+Traversal" },
  { title: "Maximum Depth of Binary Tree", companies: 7, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/maximum-depth-of-binary-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Maximum+Depth+of+Binary+Tree" },
  { title: "Symmetric Tree", companies: 7, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/symmetric-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Symmetric+Tree" },
  { title: "Balanced Binary Tree", companies: 4, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/balanced-binary-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Balanced+Binary+Tree" },
  { title: "Lowest Common Ancestor of a BST", companies: 3, difficulty: "MEDIUM", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Lowest+Common+Ancestor+of+a+BST" },
  { title: "Diameter of Binary Tree", companies: 2, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/diameter-of-binary-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Diameter+of+Binary+Tree" },
  { title: "Path Sum", companies: 2, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/path-sum", youtube: "https://www.youtube.com/results?search_query=NeetCode+Path+Sum" },
  { title: "Invert Binary Tree", companies: 1, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/invert-binary-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Invert+Binary+Tree" },
  { title: "Subtree of Another Tree", companies: 0, difficulty: "EASY", pattern: "Trees", week: 8, link: "https://leetcode.com/problems/subtree-of-another-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Subtree+of+Another+Tree" },
  // ── Week 9: Trees (part 2) — BST & harder ──
  { title: "Validate Binary Search Tree", companies: 12, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/validate-binary-search-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Validate+Binary+Search+Tree" },
  { title: "Binary Tree Maximum Path Sum", companies: 8, difficulty: "HARD", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/binary-tree-maximum-path-sum", youtube: "https://www.youtube.com/results?search_query=NeetCode+Binary+Tree+Maximum+Path+Sum" },
  { title: "Construct Binary Tree from Preorder and Inorder", companies: 6, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal", youtube: "https://www.youtube.com/results?search_query=NeetCode+Construct+Binary+Tree+from+Preorder+and+Inorder" },
  { title: "Flatten Binary Tree to Linked List", companies: 5, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list", youtube: "https://www.youtube.com/results?search_query=NeetCode+Flatten+Binary+Tree+to+Linked+List" },
  { title: "Lowest Common Ancestor of a Binary Tree", companies: 5, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Lowest+Common+Ancestor+of+a+Binary+Tree" },
  { title: "Convert Sorted Array to BST", companies: 4, difficulty: "EASY", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Convert+Sorted+Array+to+BST" },
  { title: "Path Sum II", companies: 4, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/path-sum-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Path+Sum+II" },
  { title: "Serialize and Deserialize Binary Tree", companies: 4, difficulty: "HARD", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Serialize+and+Deserialize+Binary+Tree" },
  { title: "Binary Tree Right Side View", companies: 3, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/binary-tree-right-side-view", youtube: "https://www.youtube.com/results?search_query=NeetCode+Binary+Tree+Right+Side+View" },
  { title: "Kth Smallest Element in a BST", companies: 2, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/kth-smallest-element-in-a-bst", youtube: "https://www.youtube.com/results?search_query=NeetCode+Kth+Smallest+Element+in+a+BST" },
  { title: "Count Good Nodes in Binary Tree", companies: 0, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/count-good-nodes-in-binary-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Count+Good+Nodes+in+Binary+Tree" },
  { title: "Delete Node in a BST", companies: 0, difficulty: "MEDIUM", pattern: "Trees", week: 9, link: "https://leetcode.com/problems/delete-node-in-a-bst", youtube: "https://www.youtube.com/results?search_query=NeetCode+Delete+Node+in+a+BST" },
  // ── Week 10: Tries + Heaps / Priority Queue ──
  { title: "Kth Largest Element in an Array", companies: 8, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/kth-largest-element-in-an-array", youtube: "https://www.youtube.com/results?search_query=NeetCode+Kth+Largest+Element+in+an+Array" },
  { title: "Find Median from Data Stream", companies: 5, difficulty: "HARD", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/find-median-from-data-stream", youtube: "https://www.youtube.com/results?search_query=NeetCode+Find+Median+from+Data+Stream" },
  { title: "Word Search II", companies: 4, difficulty: "HARD", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/word-search-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Word+Search+II" },
  { title: "Design Add and Search Words Data Structure", companies: 3, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/design-add-and-search-words-data-structure", youtube: "https://www.youtube.com/results?search_query=NeetCode+Design+Add+and+Search+Words+Data+Structure" },
  { title: "Last Stone Weight", companies: 3, difficulty: "EASY", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/last-stone-weight", youtube: "https://www.youtube.com/results?search_query=NeetCode+Last+Stone+Weight" },
  { title: "Implement Trie (Prefix Tree)", companies: 2, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/implement-trie-prefix-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Implement+Trie+%28Prefix+Tree%29" },
  { title: "K Closest Points to Origin", companies: 2, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/k-closest-points-to-origin", youtube: "https://www.youtube.com/results?search_query=NeetCode+K+Closest+Points+to+Origin" },
  { title: "Task Scheduler", companies: 2, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/task-scheduler", youtube: "https://www.youtube.com/results?search_query=NeetCode+Task+Scheduler" },
  { title: "Design Twitter", companies: 1, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/design-twitter", youtube: "https://www.youtube.com/results?search_query=NeetCode+Design+Twitter" },
  { title: "Kth Largest Element in a Stream", companies: 1, difficulty: "EASY", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/kth-largest-element-in-a-stream", youtube: "https://www.youtube.com/results?search_query=NeetCode+Kth+Largest+Element+in+a+Stream" },
  { title: "Reorganize String", companies: 1, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/reorganize-string", youtube: "https://www.youtube.com/results?search_query=NeetCode+Reorganize+String" },
  { title: "Top K Frequent Words", companies: 0, difficulty: "MEDIUM", pattern: "Tries + Heaps", week: 10, link: "https://leetcode.com/problems/top-k-frequent-words", youtube: "https://www.youtube.com/results?search_query=NeetCode+Top+K+Frequent+Words" },
  // ── Week 11: Backtracking ──
  { title: "Combination Sum", companies: 14, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/combination-sum", youtube: "https://www.youtube.com/results?search_query=NeetCode+Combination+Sum" },
  { title: "Word Search", companies: 14, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/word-search", youtube: "https://www.youtube.com/results?search_query=NeetCode+Word+Search" },
  { title: "Permutations", companies: 11, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/permutations", youtube: "https://www.youtube.com/results?search_query=NeetCode+Permutations" },
  { title: "Combination Sum II", companies: 10, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/combination-sum-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Combination+Sum+II" },
  { title: "Letter Combinations of a Phone Number", companies: 10, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number", youtube: "https://www.youtube.com/results?search_query=NeetCode+Letter+Combinations+of+a+Phone+Number" },
  { title: "N-Queens", companies: 10, difficulty: "HARD", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/n-queens", youtube: "https://www.youtube.com/results?search_query=NeetCode+N-Queens" },
  { title: "Subsets", companies: 10, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/subsets", youtube: "https://www.youtube.com/results?search_query=NeetCode+Subsets" },
  { title: "Permutations II", companies: 8, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/permutations-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Permutations+II" },
  { title: "Restore IP Addresses", companies: 8, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/restore-ip-addresses", youtube: "https://www.youtube.com/results?search_query=NeetCode+Restore+IP+Addresses" },
  { title: "Subsets II", companies: 8, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/subsets-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Subsets+II" },
  { title: "Combinations", companies: 7, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/combinations", youtube: "https://www.youtube.com/results?search_query=NeetCode+Combinations" },
  { title: "Palindrome Partitioning", companies: 1, difficulty: "MEDIUM", pattern: "Backtracking", week: 11, link: "https://leetcode.com/problems/palindrome-partitioning", youtube: "https://www.youtube.com/results?search_query=NeetCode+Palindrome+Partitioning" },
  // ── Week 12: Graphs (part 1) — DFS/BFS ──
  { title: "Number of Islands", companies: 11, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/number-of-islands", youtube: "https://www.youtube.com/results?search_query=NeetCode+Number+of+Islands" },
  { title: "Course Schedule", companies: 8, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/course-schedule", youtube: "https://www.youtube.com/results?search_query=NeetCode+Course+Schedule" },
  { title: "Course Schedule II", companies: 7, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/course-schedule-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Course+Schedule+II" },
  { title: "Walls and Gates", companies: 4, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/walls-and-gates", youtube: "https://www.youtube.com/results?search_query=NeetCode+Walls+and+Gates" },
  { title: "Clone Graph", companies: 3, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/clone-graph", youtube: "https://www.youtube.com/results?search_query=NeetCode+Clone+Graph" },
  { title: "Graph Valid Tree", companies: 3, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/graph-valid-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Graph+Valid+Tree" },
  { title: "Max Area of Island", companies: 3, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/max-area-of-island", youtube: "https://www.youtube.com/results?search_query=NeetCode+Max+Area+of+Island" },
  { title: "Rotting Oranges", companies: 3, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/rotting-oranges", youtube: "https://www.youtube.com/results?search_query=NeetCode+Rotting+Oranges" },
  { title: "Surrounded Regions", companies: 2, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/surrounded-regions", youtube: "https://www.youtube.com/results?search_query=NeetCode+Surrounded+Regions" },
  { title: "Number of Connected Components", companies: 1, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph", youtube: "https://www.youtube.com/results?search_query=NeetCode+Number+of+Connected+Components" },
  { title: "Flood Fill", companies: 0, difficulty: "EASY", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/flood-fill", youtube: "https://www.youtube.com/results?search_query=NeetCode+Flood+Fill" },
  { title: "Pacific Atlantic Water Flow", companies: 0, difficulty: "MEDIUM", pattern: "Graphs", week: 12, link: "https://leetcode.com/problems/pacific-atlantic-water-flow", youtube: "https://www.youtube.com/results?search_query=NeetCode+Pacific+Atlantic+Water+Flow" },
  // ── Week 13: Graphs (part 2) — Union Find / advanced ──
  { title: "Word Ladder", companies: 5, difficulty: "HARD", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/word-ladder", youtube: "https://www.youtube.com/results?search_query=NeetCode+Word+Ladder" },
  { title: "Alien Dictionary", companies: 2, difficulty: "HARD", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/alien-dictionary", youtube: "https://www.youtube.com/results?search_query=NeetCode+Alien+Dictionary" },
  { title: "Cheapest Flights Within K Stops", companies: 2, difficulty: "MEDIUM", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/cheapest-flights-within-k-stops", youtube: "https://www.youtube.com/results?search_query=NeetCode+Cheapest+Flights+Within+K+Stops" },
  { title: "Reconstruct Itinerary", companies: 2, difficulty: "HARD", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/reconstruct-itinerary", youtube: "https://www.youtube.com/results?search_query=NeetCode+Reconstruct+Itinerary" },
  { title: "Number of Provinces", companies: 1, difficulty: "MEDIUM", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/number-of-provinces", youtube: "https://www.youtube.com/results?search_query=NeetCode+Number+of+Provinces" },
  { title: "Swim in Rising Water", companies: 1, difficulty: "HARD", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/swim-in-rising-water", youtube: "https://www.youtube.com/results?search_query=NeetCode+Swim+in+Rising+Water" },
  { title: "Find the Town Judge", companies: 0, difficulty: "EASY", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/find-the-town-judge", youtube: "https://www.youtube.com/results?search_query=NeetCode+Find+the+Town+Judge" },
  { title: "Min Cost to Connect All Points", companies: 0, difficulty: "MEDIUM", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/min-cost-to-connect-all-points", youtube: "https://www.youtube.com/results?search_query=NeetCode+Min+Cost+to+Connect+All+Points" },
  { title: "Network Delay Time", companies: 0, difficulty: "MEDIUM", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/network-delay-time", youtube: "https://www.youtube.com/results?search_query=NeetCode+Network+Delay+Time" },
  { title: "Redundant Connection", companies: 0, difficulty: "MEDIUM", pattern: "Advanced Graphs", week: 13, link: "https://leetcode.com/problems/redundant-connection", youtube: "https://www.youtube.com/results?search_query=NeetCode+Redundant+Connection" },
  // ── Week 14: 1-D Dynamic Programming ──
  { title: "Longest Palindromic Substring", companies: 15, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/longest-palindromic-substring", youtube: "https://www.youtube.com/results?search_query=NeetCode+Longest+Palindromic+Substring" },
  { title: "Decode Ways", companies: 13, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/decode-ways", youtube: "https://www.youtube.com/results?search_query=NeetCode+Decode+Ways" },
  { title: "Climbing Stairs", companies: 12, difficulty: "EASY", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/climbing-stairs", youtube: "https://www.youtube.com/results?search_query=NeetCode+Climbing+Stairs" },
  { title: "House Robber", companies: 9, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/house-robber", youtube: "https://www.youtube.com/results?search_query=NeetCode+House+Robber" },
  { title: "Maximum Product Subarray", companies: 7, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/maximum-product-subarray", youtube: "https://www.youtube.com/results?search_query=NeetCode+Maximum+Product+Subarray" },
  { title: "Coin Change", companies: 5, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/coin-change", youtube: "https://www.youtube.com/results?search_query=NeetCode+Coin+Change" },
  { title: "House Robber II", companies: 4, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/house-robber-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+House+Robber+II" },
  { title: "Word Break", companies: 4, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/word-break", youtube: "https://www.youtube.com/results?search_query=NeetCode+Word+Break" },
  { title: "Longest Increasing Subsequence", companies: 3, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/longest-increasing-subsequence", youtube: "https://www.youtube.com/results?search_query=NeetCode+Longest+Increasing+Subsequence" },
  { title: "Palindromic Substrings", companies: 3, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/palindromic-substrings", youtube: "https://www.youtube.com/results?search_query=NeetCode+Palindromic+Substrings" },
  { title: "Partition Equal Subset Sum", companies: 2, difficulty: "MEDIUM", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/partition-equal-subset-sum", youtube: "https://www.youtube.com/results?search_query=NeetCode+Partition+Equal+Subset+Sum" },
  { title: "Min Cost Climbing Stairs", companies: 0, difficulty: "EASY", pattern: "1-D DP", week: 14, link: "https://leetcode.com/problems/min-cost-climbing-stairs", youtube: "https://www.youtube.com/results?search_query=NeetCode+Min+Cost+Climbing+Stairs" },
  // ── Week 15: 2-D Dynamic Programming (part 1) ──
  { title: "Unique Paths", companies: 11, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/unique-paths", youtube: "https://www.youtube.com/results?search_query=NeetCode+Unique+Paths" },
  { title: "Minimum Path Sum", companies: 10, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/minimum-path-sum", youtube: "https://www.youtube.com/results?search_query=NeetCode+Minimum+Path+Sum" },
  { title: "Unique Paths II", companies: 9, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/unique-paths-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Unique+Paths+II" },
  { title: "Maximal Square", companies: 7, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/maximal-square", youtube: "https://www.youtube.com/results?search_query=NeetCode+Maximal+Square" },
  { title: "Interleaving String", companies: 6, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/interleaving-string", youtube: "https://www.youtube.com/results?search_query=NeetCode+Interleaving+String" },
  { title: "Best Time to Buy and Sell Stock with Cooldown", companies: 2, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown", youtube: "https://www.youtube.com/results?search_query=NeetCode+Best+Time+to+Buy+and+Sell+Stock+with+Cooldown" },
  { title: "Longest Common Subsequence", companies: 2, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/longest-common-subsequence", youtube: "https://www.youtube.com/results?search_query=NeetCode+Longest+Common+Subsequence" },
  { title: "Dungeon Game", companies: 1, difficulty: "HARD", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/dungeon-game", youtube: "https://www.youtube.com/results?search_query=NeetCode+Dungeon+Game" },
  { title: "Coin Change II", companies: 0, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/coin-change-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Coin+Change+II" },
  { title: "Target Sum", companies: 0, difficulty: "MEDIUM", pattern: "2-D DP", week: 15, link: "https://leetcode.com/problems/target-sum", youtube: "https://www.youtube.com/results?search_query=NeetCode+Target+Sum" },
  // ── Week 16: 2-D Dynamic Programming (part 2) ──
  { title: "Edit Distance", companies: 11, difficulty: "MEDIUM", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/edit-distance", youtube: "https://www.youtube.com/results?search_query=NeetCode+Edit+Distance" },
  { title: "Maximal Rectangle", companies: 11, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/maximal-rectangle", youtube: "https://www.youtube.com/results?search_query=NeetCode+Maximal+Rectangle" },
  { title: "Regular Expression Matching", companies: 10, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/regular-expression-matching", youtube: "https://www.youtube.com/results?search_query=NeetCode+Regular+Expression+Matching" },
  { title: "Wildcard Matching", companies: 10, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/wildcard-matching", youtube: "https://www.youtube.com/results?search_query=NeetCode+Wildcard+Matching" },
  { title: "Longest Valid Parentheses", companies: 9, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/longest-valid-parentheses", youtube: "https://www.youtube.com/results?search_query=NeetCode+Longest+Valid+Parentheses" },
  { title: "Distinct Subsequences", companies: 3, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/distinct-subsequences", youtube: "https://www.youtube.com/results?search_query=NeetCode+Distinct+Subsequences" },
  { title: "Longest Increasing Path in a Matrix", companies: 3, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix", youtube: "https://www.youtube.com/results?search_query=NeetCode+Longest+Increasing+Path+in+a+Matrix" },
  { title: "Burst Balloons", companies: 2, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/burst-balloons", youtube: "https://www.youtube.com/results?search_query=NeetCode+Burst+Balloons" },
  { title: "Minimum Cost to Cut a Stick", companies: 0, difficulty: "HARD", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/min-cost-to-cut-a-stick", youtube: "https://www.youtube.com/results?search_query=NeetCode+Minimum+Cost+to+Cut+a+Stick" },
  { title: "Stone Game", companies: 0, difficulty: "MEDIUM", pattern: "2-D DP", week: 16, link: "https://leetcode.com/problems/stone-game", youtube: "https://www.youtube.com/results?search_query=NeetCode+Stone+Game" },
  // ── Week 17: Greedy + Intervals ──
  { title: "Merge Intervals", companies: 21, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/merge-intervals", youtube: "https://www.youtube.com/results?search_query=NeetCode+Merge+Intervals" },
  { title: "Maximum Subarray", companies: 17, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/maximum-subarray", youtube: "https://www.youtube.com/results?search_query=NeetCode+Maximum+Subarray" },
  { title: "Jump Game", companies: 15, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/jump-game", youtube: "https://www.youtube.com/results?search_query=NeetCode+Jump+Game" },
  { title: "Jump Game II", companies: 15, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/jump-game-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Jump+Game+II" },
  { title: "Insert Interval", companies: 11, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/insert-interval", youtube: "https://www.youtube.com/results?search_query=NeetCode+Insert+Interval" },
  { title: "Meeting Rooms II", companies: 5, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/meeting-rooms-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Meeting+Rooms+II" },
  { title: "Gas Station", companies: 3, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/gas-station", youtube: "https://www.youtube.com/results?search_query=NeetCode+Gas+Station" },
  { title: "Minimum Arrows to Burst Balloons", companies: 2, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons", youtube: "https://www.youtube.com/results?search_query=NeetCode+Minimum+Arrows+to+Burst+Balloons" },
  { title: "Hand of Straights", companies: 0, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/hand-of-straights", youtube: "https://www.youtube.com/results?search_query=NeetCode+Hand+of+Straights" },
  { title: "Non-overlapping Intervals", companies: 0, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/non-overlapping-intervals", youtube: "https://www.youtube.com/results?search_query=NeetCode+Non-overlapping+Intervals" },
  { title: "Partition Labels", companies: 0, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/partition-labels", youtube: "https://www.youtube.com/results?search_query=NeetCode+Partition+Labels" },
  { title: "Valid Parenthesis String", companies: 0, difficulty: "MEDIUM", pattern: "Greedy + Intervals", week: 17, link: "https://leetcode.com/problems/valid-parenthesis-string", youtube: "https://www.youtube.com/results?search_query=NeetCode+Valid+Parenthesis+String" },
  // ── Week 18: Math & Geometry + Bit Manipulation ──
  { title: "Spiral Matrix", companies: 14, difficulty: "MEDIUM", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/spiral-matrix", youtube: "https://www.youtube.com/results?search_query=NeetCode+Spiral+Matrix" },
  { title: "Pow(x, n)", companies: 13, difficulty: "MEDIUM", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/powx-n", youtube: "https://www.youtube.com/results?search_query=NeetCode+Pow%28x%2C+n%29" },
  { title: "Rotate Image", companies: 12, difficulty: "MEDIUM", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/rotate-image", youtube: "https://www.youtube.com/results?search_query=NeetCode+Rotate+Image" },
  { title: "Set Matrix Zeroes", companies: 10, difficulty: "MEDIUM", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/set-matrix-zeroes", youtube: "https://www.youtube.com/results?search_query=NeetCode+Set+Matrix+Zeroes" },
  { title: "Plus One", companies: 9, difficulty: "EASY", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/plus-one", youtube: "https://www.youtube.com/results?search_query=NeetCode+Plus+One" },
  { title: "Multiply Strings", companies: 8, difficulty: "MEDIUM", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/multiply-strings", youtube: "https://www.youtube.com/results?search_query=NeetCode+Multiply+Strings" },
  { title: "Missing Number", companies: 3, difficulty: "EASY", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/missing-number", youtube: "https://www.youtube.com/results?search_query=NeetCode+Missing+Number" },
  { title: "Single Number", companies: 3, difficulty: "EASY", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/single-number", youtube: "https://www.youtube.com/results?search_query=NeetCode+Single+Number" },
  { title: "Happy Number", companies: 2, difficulty: "EASY", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/happy-number", youtube: "https://www.youtube.com/results?search_query=NeetCode+Happy+Number" },
  { title: "Reverse Bits", companies: 2, difficulty: "EASY", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/reverse-bits", youtube: "https://www.youtube.com/results?search_query=NeetCode+Reverse+Bits" },
  { title: "Counting Bits", companies: 1, difficulty: "EASY", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/counting-bits", youtube: "https://www.youtube.com/results?search_query=NeetCode+Counting+Bits" },
  { title: "Number of 1 Bits", companies: 0, difficulty: "EASY", pattern: "Math & Bit Manipulation", week: 18, link: "https://leetcode.com/problems/number-of-1-bits", youtube: "https://www.youtube.com/results?search_query=NeetCode+Number+of+1+Bits" },
  // ── Week 19: Buffer + full Phase A–C revision ──
  { title: "Text Justification", companies: 16, difficulty: "HARD", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/text-justification", youtube: "https://www.youtube.com/results?search_query=NeetCode+Text+Justification" },
  { title: "Integer to Roman", companies: 15, difficulty: "MEDIUM", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/integer-to-roman", youtube: "https://www.youtube.com/results?search_query=NeetCode+Integer+to+Roman" },
  { title: "Roman to Integer", companies: 11, difficulty: "EASY", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/roman-to-integer", youtube: "https://www.youtube.com/results?search_query=NeetCode+Roman+to+Integer" },
  { title: "String to Integer (atoi)", companies: 11, difficulty: "MEDIUM", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/string-to-integer-atoi", youtube: "https://www.youtube.com/results?search_query=NeetCode+String+to+Integer+%28atoi%29" },
  { title: "Zigzag Conversion", companies: 10, difficulty: "MEDIUM", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/zigzag-conversion", youtube: "https://www.youtube.com/results?search_query=NeetCode+Zigzag+Conversion" },
  { title: "Add Binary", companies: 8, difficulty: "EASY", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/add-binary", youtube: "https://www.youtube.com/results?search_query=NeetCode+Add+Binary" },
  { title: "Count and Say", companies: 7, difficulty: "MEDIUM", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/count-and-say", youtube: "https://www.youtube.com/results?search_query=NeetCode+Count+and+Say" },
  { title: "Valid Number", companies: 6, difficulty: "HARD", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/valid-number", youtube: "https://www.youtube.com/results?search_query=NeetCode+Valid+Number" },
  { title: "Rotate Array", companies: 4, difficulty: "MEDIUM", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/rotate-array", youtube: "https://www.youtube.com/results?search_query=NeetCode+Rotate+Array" },
  { title: "Excel Sheet Column Number", companies: 0, difficulty: "EASY", pattern: "Revision — mixed", week: 19, link: "https://leetcode.com/problems/excel-sheet-column-number", youtube: "https://www.youtube.com/results?search_query=NeetCode+Excel+Sheet+Column+Number" },
  // ── Week 20: Timed OA simulation — mixed ──
  { title: "Insert Delete GetRandom O(1)", companies: 7, difficulty: "MEDIUM", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/insert-delete-getrandom-o1", youtube: "https://www.youtube.com/results?search_query=NeetCode+Insert+Delete+GetRandom+O%281%29" },
  { title: "Substring with Concatenation of All Words", companies: 6, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/substring-with-concatenation-of-all-words", youtube: "https://www.youtube.com/results?search_query=NeetCode+Substring+with+Concatenation+of+All+Words" },
  { title: "Maximum Profit in Job Scheduling", companies: 5, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/maximum-profit-in-job-scheduling", youtube: "https://www.youtube.com/results?search_query=NeetCode+Maximum+Profit+in+Job+Scheduling" },
  { title: "Word Break II", companies: 4, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/word-break-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Word+Break+II" },
  { title: "Longest String Chain", companies: 3, difficulty: "MEDIUM", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/longest-string-chain", youtube: "https://www.youtube.com/results?search_query=NeetCode+Longest+String+Chain" },
  { title: "Maximum Frequency Stack", companies: 3, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/maximum-frequency-stack", youtube: "https://www.youtube.com/results?search_query=NeetCode+Maximum+Frequency+Stack" },
  { title: "String Compression", companies: 3, difficulty: "MEDIUM", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/string-compression", youtube: "https://www.youtube.com/results?search_query=NeetCode+String+Compression" },
  { title: "The Skyline Problem", companies: 3, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/the-skyline-problem", youtube: "https://www.youtube.com/results?search_query=NeetCode+The+Skyline+Problem" },
  { title: "Design Hit Counter", companies: 2, difficulty: "MEDIUM", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/design-hit-counter", youtube: "https://www.youtube.com/results?search_query=NeetCode+Design+Hit+Counter" },
  { title: "Number of Islands II", companies: 2, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/number-of-islands-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Number+of+Islands+II" },
  { title: "Range Sum Query 2D Immutable", companies: 2, difficulty: "MEDIUM", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/range-sum-query-2d-immutable", youtube: "https://www.youtube.com/results?search_query=NeetCode+Range+Sum+Query+2D+Immutable" },
  { title: "Shortest Path with Obstacles Elimination", companies: 2, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination", youtube: "https://www.youtube.com/results?search_query=NeetCode+Shortest+Path+with+Obstacles+Elimination" },
  { title: "Trapping Rain Water II", companies: 1, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/trapping-rain-water-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Trapping+Rain+Water+II" },
  { title: "Max Sum 3 Non-Overlapping Subarrays", companies: 0, difficulty: "HARD", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/maximum-sum-of-3-non-overlapping-subarrays", youtube: "https://www.youtube.com/results?search_query=NeetCode+Max+Sum+3+Non-Overlapping+Subarrays" },
  { title: "Maximum Swap", companies: 0, difficulty: "MEDIUM", pattern: "Timed OA — mixed", week: 20, link: "https://leetcode.com/problems/maximum-swap", youtube: "https://www.youtube.com/results?search_query=NeetCode+Maximum+Swap" },
  // ── Week 21: Company-tagged sets — Amazon/Microsoft/Google ──
  { title: "Largest Number", companies: 4, difficulty: "MEDIUM", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/largest-number", youtube: "https://www.youtube.com/results?search_query=NeetCode+Largest+Number" },
  { title: "Candy", companies: 3, difficulty: "HARD", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/candy", youtube: "https://www.youtube.com/results?search_query=NeetCode+Candy" },
  { title: "Cherry Pickup", companies: 2, difficulty: "HARD", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/cherry-pickup", youtube: "https://www.youtube.com/results?search_query=NeetCode+Cherry+Pickup" },
  { title: "Design Browser History", companies: 2, difficulty: "MEDIUM", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/design-browser-history", youtube: "https://www.youtube.com/results?search_query=NeetCode+Design+Browser+History" },
  { title: "Design In-Memory File System", companies: 2, difficulty: "HARD", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/design-in-memory-file-system", youtube: "https://www.youtube.com/results?search_query=NeetCode+Design+In-Memory+File+System" },
  { title: "Employee Free Time", companies: 2, difficulty: "HARD", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/employee-free-time", youtube: "https://www.youtube.com/results?search_query=NeetCode+Employee+Free+Time" },
  { title: "Random Pick with Weight", companies: 2, difficulty: "MEDIUM", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/random-pick-with-weight", youtube: "https://www.youtube.com/results?search_query=NeetCode+Random+Pick+with+Weight" },
  { title: "Shortest Bridge", companies: 2, difficulty: "MEDIUM", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/shortest-bridge", youtube: "https://www.youtube.com/results?search_query=NeetCode+Shortest+Bridge" },
  { title: "Sliding Window Median", companies: 2, difficulty: "HARD", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/sliding-window-median", youtube: "https://www.youtube.com/results?search_query=NeetCode+Sliding+Window+Median" },
  { title: "Snapshot Array", companies: 2, difficulty: "MEDIUM", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/snapshot-array", youtube: "https://www.youtube.com/results?search_query=NeetCode+Snapshot+Array" },
  { title: "Task Scheduler II", companies: 2, difficulty: "MEDIUM", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/task-scheduler-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Task+Scheduler+II" },
  { title: "Design Search Autocomplete System", companies: 1, difficulty: "HARD", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/design-search-autocomplete-system", youtube: "https://www.youtube.com/results?search_query=NeetCode+Design+Search+Autocomplete+System" },
  { title: "Group Shifted Strings", companies: 1, difficulty: "MEDIUM", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/group-shifted-strings", youtube: "https://www.youtube.com/results?search_query=NeetCode+Group+Shifted+Strings" },
  { title: "Logger Rate Limiter", companies: 1, difficulty: "EASY", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/logger-rate-limiter", youtube: "https://www.youtube.com/results?search_query=NeetCode+Logger+Rate+Limiter" },
  { title: "Meeting Rooms", companies: 0, difficulty: "EASY", pattern: "Company set — Amazon/MS/Google", week: 21, link: "https://leetcode.com/problems/meeting-rooms", youtube: "https://www.youtube.com/results?search_query=NeetCode+Meeting+Rooms" },
  // ── Week 22: Company-tagged sets — bio-AI & general ML targets ──
  { title: "Design Tic-Tac-Toe", companies: 3, difficulty: "MEDIUM", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/design-tic-tac-toe", youtube: "https://www.youtube.com/results?search_query=NeetCode+Design+Tic-Tac-Toe" },
  { title: "Smallest Range Covering K Lists", companies: 2, difficulty: "HARD", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists", youtube: "https://www.youtube.com/results?search_query=NeetCode+Smallest+Range+Covering+K+Lists" },
  { title: "Accounts Merge", companies: 1, difficulty: "MEDIUM", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/accounts-merge", youtube: "https://www.youtube.com/results?search_query=NeetCode+Accounts+Merge" },
  { title: "Car Pooling", companies: 1, difficulty: "MEDIUM", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/car-pooling", youtube: "https://www.youtube.com/results?search_query=NeetCode+Car+Pooling" },
  { title: "Data Stream as Disjoint Intervals", companies: 1, difficulty: "HARD", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/data-stream-as-disjoint-intervals", youtube: "https://www.youtube.com/results?search_query=NeetCode+Data+Stream+as+Disjoint+Intervals" },
  { title: "Evaluate Division", companies: 1, difficulty: "MEDIUM", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/evaluate-division", youtube: "https://www.youtube.com/results?search_query=NeetCode+Evaluate+Division" },
  { title: "Find K Pairs with Smallest Sums", companies: 1, difficulty: "MEDIUM", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums", youtube: "https://www.youtube.com/results?search_query=NeetCode+Find+K+Pairs+with+Smallest+Sums" },
  { title: "Frog Jump", companies: 1, difficulty: "HARD", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/frog-jump", youtube: "https://www.youtube.com/results?search_query=NeetCode+Frog+Jump" },
  { title: "Number of Distinct Islands", companies: 1, difficulty: "MEDIUM", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/number-of-distinct-islands", youtube: "https://www.youtube.com/results?search_query=NeetCode+Number+of+Distinct+Islands" },
  { title: "Remove Invalid Parentheses", companies: 1, difficulty: "HARD", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/remove-invalid-parentheses", youtube: "https://www.youtube.com/results?search_query=NeetCode+Remove+Invalid+Parentheses" },
  { title: "Russian Doll Envelopes", companies: 1, difficulty: "HARD", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/russian-doll-envelopes", youtube: "https://www.youtube.com/results?search_query=NeetCode+Russian+Doll+Envelopes" },
  { title: "Two Sum III", companies: 1, difficulty: "EASY", pattern: "Company set — bio-AI & ML", week: 22, link: "https://leetcode.com/problems/two-sum-iii-data-structure-design", youtube: "https://www.youtube.com/results?search_query=NeetCode+Two+Sum+III" },
  // ── Week 23: Final polish — weak spots, speed ──
  { title: "Diameter of N-Ary Tree", companies: 1, difficulty: "MEDIUM", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/diameter-of-n-ary-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Diameter+of+N-Ary+Tree" },
  { title: "Find K-th Smallest Pair Distance", companies: 1, difficulty: "HARD", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/find-k-th-smallest-pair-distance", youtube: "https://www.youtube.com/results?search_query=NeetCode+Find+K-th+Smallest+Pair+Distance" },
  { title: "IPO", companies: 1, difficulty: "HARD", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/ipo", youtube: "https://www.youtube.com/results?search_query=NeetCode+IPO" },
  { title: "Kth Smallest in Sorted Matrix", companies: 1, difficulty: "MEDIUM", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix", youtube: "https://www.youtube.com/results?search_query=NeetCode+Kth+Smallest+in+Sorted+Matrix" },
  { title: "Vertical Order Traversal of a Binary Tree", companies: 1, difficulty: "HARD", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree", youtube: "https://www.youtube.com/results?search_query=NeetCode+Vertical+Order+Traversal+of+a+Binary+Tree" },
  { title: "Design Circular Queue", companies: 0, difficulty: "MEDIUM", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/design-circular-queue", youtube: "https://www.youtube.com/results?search_query=NeetCode+Design+Circular+Queue" },
  { title: "Expression Add Operators", companies: 0, difficulty: "HARD", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/expression-add-operators", youtube: "https://www.youtube.com/results?search_query=NeetCode+Expression+Add+Operators" },
  { title: "Integer to English Words", companies: 0, difficulty: "HARD", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/integer-to-english-words", youtube: "https://www.youtube.com/results?search_query=NeetCode+Integer+to+English+Words" },
  { title: "Longest Word in Dictionary", companies: 0, difficulty: "MEDIUM", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/longest-word-in-dictionary", youtube: "https://www.youtube.com/results?search_query=NeetCode+Longest+Word+in+Dictionary" },
  { title: "Word Wrap", companies: 0, difficulty: "HARD", pattern: "Final polish", week: 23, link: "https://leetcode.com/problems/text-justification-ii", youtube: "https://www.youtube.com/results?search_query=NeetCode+Word+Wrap" },
];

// Week topic labels — mirror the 23-week roadmap. Used for week headers.
export const WEEK_TOPICS: Record<number, string> = {
  1: "Python DS rebuild + Arrays & Hashing",
  2: "Two Pointers + intro Sliding Window",
  3: "Sliding Window (full)",
  4: "Stack",
  5: "Binary Search",
  6: "Linked List (part 1) + buffer/revision",
  7: "Linked List (part 2)",
  8: "Trees (part 1) — traversal & basics",
  9: "Trees (part 2) — BST & harder",
  10: "Tries + Heaps / Priority Queue",
  11: "Backtracking",
  12: "Graphs (part 1) — DFS/BFS",
  13: "Graphs (part 2) — Union Find / advanced",
  14: "1-D Dynamic Programming",
  15: "2-D Dynamic Programming (part 1)",
  16: "2-D Dynamic Programming (part 2)",
  17: "Greedy + Intervals",
  18: "Math & Geometry + Bit Manipulation",
  19: "Buffer + full Phase A–C revision",
  20: "Timed OA simulation — mixed",
  21: "Company-tagged sets — Amazon/Microsoft/Google",
  22: "Company-tagged sets — bio-AI & general ML targets",
  23: "Final polish — weak spots, speed",
};

// Week date ranges from the roadmap (optional UI use).
export const WEEK_DATES: Record<number, string> = {
  1: "22 Jun – 28 Jun",
  2: "29 Jun – 05 Jul",
  3: "06 Jul – 12 Jul",
  4: "13 Jul – 19 Jul",
  5: "20 Jul – 26 Jul",
  6: "27 Jul – 02 Aug",
  7: "03 Aug – 09 Aug",
  8: "10 Aug – 16 Aug",
  9: "17 Aug – 23 Aug",
  10: "24 Aug – 30 Aug",
  11: "31 Aug – 06 Sep",
  12: "07 Sep – 13 Sep",
  13: "14 Sep – 20 Sep",
  14: "21 Sep – 27 Sep",
  15: "28 Sep – 04 Oct",
  16: "05 Oct – 11 Oct",
  17: "12 Oct – 18 Oct",
  18: "19 Oct – 25 Oct",
  19: "26 Oct – 01 Nov",
  20: "02 Nov – 08 Nov",
  21: "09 Nov – 15 Nov",
  22: "16 Nov – 22 Nov",
  23: "23 Nov – 29 Nov",
};

// Phase grouping (Foundation / Core / Advanced / Mock).
export const PHASES: { name: string; weeks: number[]; blurb: string }[] = [
  { name: "Foundation", weeks: [1, 2, 3, 4, 5, 6], blurb: "Arrays → Binary Search → Linked Lists" },
  { name: "Core", weeks: [7, 8, 9, 10, 11, 12, 13], blurb: "Trees, Tries, Heaps, Backtracking, Graphs" },
  { name: "Advanced", weeks: [14, 15, 16, 17, 18, 19], blurb: "DP, Greedy, Intervals, Math, Bits" },
  { name: "Mock & Polish", weeks: [20, 21, 22, 23], blurb: "Timed OAs, company sets, revision" },
];